// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: haptic_knob

#include "../ui.h"

void ui_comp_Arc2_create_hook(lv_obj_t * comp)
{
}
