// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: haptic_knob

#include "../ui.h"

// COMPONENT Arc2

lv_obj_t * ui_Arc2_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Arc2;
    cui_Arc2 = lv_arc_create(comp_parent);
    lv_obj_set_width(cui_Arc2, 150);
    lv_obj_set_height(cui_Arc2, 150);
    lv_obj_set_align(cui_Arc2, LV_ALIGN_CENTER);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_ARC2_NUM);
    children[UI_COMP_ARC2_ARC2] = cui_Arc2;
    lv_obj_add_event_cb(cui_Arc2, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Arc2, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Arc2_create_hook(cui_Arc2);
    return cui_Arc2;
}

