// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: haptic_knob

#ifndef _HAPTIC_KNOB_UI_H
#define _HAPTIC_KNOB_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_events.h"
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Arc2;
void ui_event_Label1(lv_event_t * e);
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Dropdown2;
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
