// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: haptic_knob

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void init_action(lv_event_t * e);
void encoder_cb(lv_event_t * e);
void damped_cb(lv_event_t * e);
void light_cb(lv_event_t * e);
void swich_cb(lv_event_t * e);
void light_tuning(lv_event_t * e);
void swich_status(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
