// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: haptic_knob

#include "ui.h"
#include "lv_port/include/lv_port_indev.h"
#include "knob.h"
#include "knob_task.h"

void init_action(lv_event_t * e)
{
    lv_group_t *g = lv_group_create();
    lv_group_set_default(g);
    lv_indev_set_group(indev_encoder, g);
    lv_group_add_obj(g,ui_Arc2);
}

void update_lable(lv_event_t * e)
{
    lv_obj_t *lable = lv_event_get_current_target(e);
    lv_label_set_text_fmt(lable,"%d", knob_encoder_read(knob));
}

void encoder_cb(lv_event_t * e)
{
	// Your code here
}

void damped_cb(lv_event_t * e)
{
	// Your code here
}

void light_cb(lv_event_t * e)
{
	// Your code here
}
